--- 
- 
  become: true
  gather_facts: false
  hosts: all
  name: "Anible POC"
  strategy: free
  tasks: 
    - 
      file: "path=/opt state=directory"
      name: "Create /opt directory"
    - 
      get_url: "dest=/opt/apache-maven-3.8.5-bin.tar.gz url=http://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz"
      name: "Download Maven3"
    - 
      action: "command creates=/opt/maven chdir=/opt tar zxvf /opt/apache-maven-3.8.5-bin.tar.gz"
      name: "Unpack Maven3"
    - 
      file: "path=/opt/maven src=/opt/apache-maven-3.8.5 state=link"
      name: "Create Maven3 directory link"
    - 
      action: "command update-alternatives --install /usr/bin/mvn mvn /opt/maven/bin/mvn 1"
      name: "Set mvn link"
    - 
      name: "Export Maven Path"
      shell: "export PATH=/opt/apache-maven-3.8.5/bin:$PATH"
    - 
      name: "echo PATH"
      shell: "echo $PATH"
    - 
      file: "path=/opt/apache-maven-3.8.5-bin.tar.gz state=absent"
      name: "Remove Maven3 archive"
    - 
      git: 
        clone: true
        dest: /opt/git-repo
        repo: "https://github.ibm.com/Boomerang-Delivery/queuedepthdashboard.git"
        update: true
        version: master
      name: "Clone a Git repository"
      register: gitclone
    - 
      command: "mvn -f /opt/git-repo/pom.xml clean install"
      name: "Run MVN Clean install"
      when: gitclone.changed
    - 
      name: "Execute Jar File"
      shell: "java -cp /opt/git-repo/target/jb-hello-world-maven-0.1.0.jar hello.HelloWorld"