---
- name: "SAP TCode Monitor POC"
  become: true
  gather_facts: false
  hosts: localhost
  strategy: free
  tasks: 
      
    - name: "Clone Git repository"
      ansible.windows.win_command:
        repo: "https://github.com/mriganka20/Ansible_POC.git"
        dest: C:\Users\ansibleuser\Desktop\DWAutomation\Ansible_POC\AnsibleCodes
        clone: yes
        update: yes
      
    - name: "Execute Python script"
      command: C:\Users\ansibleuser\Desktop\DWAutomation\Ansible_POC\AnsibleCodes\PY_SAP_SM50_TCodeMonitor.py
