---
- name: "SAP TCode Monitor POC"
  become: true
  gather_facts: false
  hosts: winhost
  strategy: free
  tasks: 
      
    - name: "Clone Git repository
     win_command: >
    "C:\\Program Files\\Git\\bin\\git.exe"
    "--no-pager"
    "clone"
    "https://github.com/mriganka20/Ansible_POC.git"
    "C:\\Users\\ansibleuser\\Desktop\\DWAutomation\\AnsiblePOC\\AnsibleCodes"
    "--recursive"
      
    - name: "Execute Python script"
      win_command: python C:\\Users\\ansibleuser\\Desktop\\DWAutomation\\Ansible_POC\\AnsibleCodes\\PY_SAP_SM50_TCodeMonitor.py
